### ISSUE TITLE
[Bug]: 使用Hexon solitude主题后无法正确读取Hexo版本

### ISSUE THREAD

**Issue by ClassmateShen** [everfu/hexo-theme-solitude#291]
### 前置确认

- [X] 我确认我运行的是最新版本的主题，并且安装了所需的依赖，在[FAQS](https://solitude-docs.efu.me/faq)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Mac/Linux

### 运行的Hexo版本是?

Hexo 7.0.0

### 你所使用的主题版本是稳定/最新?

稳定版（main）

### 问题描述 😯

如题，我的Hexo版本是7.2.0，但一旦使用solitude主题后hexon程序就会提示版本过低，但如果用默认的landscape就不会有问题，想问一下是不是solitude主题会修改Hexo版本配置导致Hexon程序无法获取到对应真实Hexo的版本

**Comment by everfu** [comment]
不会吧，你可以在项目执行一下：
```bash
npm ls --depth 0
```
把结果发出来

**Comment by ClassmateShen** [comment]
> 不会吧，你可以在项目执行一下：
> 
> ```shell
> npm ls --depth 0
> ```
> 
> 把结果发出来

hexo-site@0.0.0 /blog-path
├── hexo-generator-archive@2.0.0
├── hexo-generator-category@2.0.0
├── hexo-generator-index@3.0.0
├── hexo-generator-tag@2.0.0
├── hexo-renderer-ejs@2.0.0
├── hexo-renderer-marked@6.3.0
├── hexo-renderer-pug@3.0.0
├── hexo-renderer-stylus@3.0.1
├── hexo-server@3.0.0
├── hexo-theme-landscape@1.0.0
├── hexo-theme-solitude@1.11.0
└── hexo@7.2.0

**Comment by everfu** [comment]
报错是什么

**Comment by ClassmateShen** [comment]
```
> hexon@0.12.6 start /www/wwwroot/blog.shenkx.com/hexon
> cd ./server && pnpm start


> @ start /www/wwwroot/blog.shenkx.com/hexon/server
> cross-env DEBUG=null NODE_ENV=production && node dist/index.js

{ username: undefined, password: undefined }
{ port: undefined }
{ base: undefined }
Server running on http://localhost:5877
[hexo-instance-service][2024-05-27 11:25:51.980] real init start
INFO  Validating config
INFO  
  ===================================================================
       #####  ####  #     #####  ###### #     # ######   ######
      #      #    # #       #      #    #     # #      # #
       ##### #    # #       #      #    #     # #      # ######
           # #    # #       #      #    #     # #      # #
      ######  ####  ##### #####    #      ###   ######   ######
                            1.11.0
  ===================================================================
  GitHub: https://github.com/valor-x/hexo-theme-solitude
  
INFO  Start processing
ERROR 请把 Hexo 升级到 V7.0.0 或更高的版本！
ERROR Please upgrade your Hexo to V7.0.0 or higher!
ELIFECYCLE  Command failed with exit code 255.
ELIFECYCLE  Command failed with exit code 255.```

**Comment by everfu** [comment]
你这是两个不同的吧，一个在服务器一个在本地，考虑是服务器的版本太低了

**Comment by ClassmateShen** [comment]
> 你这是两个不同的吧，一个在服务器一个在本地，考虑是服务器的版本太低了

没有啊，都是在服务器上的，hexo和hexon都在服务器上，并且hexo版本是7.2.0，hexon版本是0.12.6

**Comment by everfu** [comment]
> > 你这是两个不同的吧，一个在服务器一个在本地，考虑是服务器的版本太低了
> 
> 没有啊，都是在服务器上的，hexo和hexon都在服务器上，并且hexo版本是7.2.0，hexon版本是0.12.6

hexoon是什么，扔个地址

**Comment by ClassmateShen** [comment]
> > > 你这是两个不同的吧，一个在服务器一个在本地，考虑是服务器的版本太低了
> > 
> > 
> > 没有啊，都是在服务器上的，hexo和hexon都在服务器上，并且hexo版本是7.2.0，hexon版本是0.12.6
> 
> hexoon是什么，扔个地址

https://github.com/gethexon/hexon
辛苦佬看一下，就是一个可视化的Hexo文章编辑器

**Comment by everfu** [comment]
> > > > 你这是两个不同的吧，一个在服务器一个在本地，考虑是服务器的版本太低了
> > > 
> > > 
> > > 没有啊，都是在服务器上的，hexo和hexon都在服务器上，并且hexo版本是7.2.0，hexon版本是0.12.6
> > 
> > 
> > hexoon是什么，扔个地址
> 
> https://github.com/gethexon/hexon 辛苦佬看一下，就是一个可视化的Hexo文章编辑器

我觉得问题出在 hexoon，如果你在本地单独使用hexo测试没问题的话

**Comment by ClassmateShen** [comment]
但用默认主题没问题，不知道为什么

**Comment by everfu** [comment]
默认主题兼容以前的版本
