### ISSUE TITLE
[Feature]: galleryGroup 相册图库支持分行参数

### ISSUE THREAD

**Issue by NooAcc** [everfu/hexo-theme-solitude#297]
### 前置确认

- [X] 我确认我运行的是最新版本的主题，并且安装了所需的依赖，在[FAQS](https://solitude-docs.efu.me/faq)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的Hexo版本是?

Hexo 7.0.0

### 你所使用的主题版本是稳定/最新?

稳定版（main）

### 问题描述 😯

问题描述：
使用galleryGroup标签时，galleryGroup的封面会生成在一行，封面越多越密集。
![image](https://github.com/everfu/hexo-theme-solitude/assets/101051650/845fb869-27a7-44ec-a160-24a5bea0ca92)

下面是我复现bug时使用的index.md
[index.md](https://github.com/user-attachments/files/15543837/index.md)

### 终端日志 📒

"npm ls -dept 0"的结果如下：
```
hexo-site@0.0.0 D:\SoftWare\Code\Github\solitude
+-- hexo-generator-archive@2.0.0
+-- hexo-generator-category@2.0.0
+-- hexo-generator-index@3.0.0
+-- hexo-generator-tag@2.0.0
+-- hexo-renderer-ejs@2.0.0
+-- hexo-renderer-marked@6.3.0
+-- hexo-renderer-pug@3.0.0
+-- hexo-renderer-stylus@3.0.1
+-- hexo-server@3.0.0
+-- hexo-theme-landscape@1.0.0
`-- hexo@7.2.0
```

"hexo s -debug"没有产生报错，就不贴上来了。

**Comment by everfu** [comment]
有没有试过多个gallerygroup，逻辑是对的

**Comment by everfu** [comment]
```markdown
<div class="gallery-group-main">
{% galleryGroup '壁紙' '收藏的一些壁紙' '/' https://s3.qjqq.cn/47/661f408a2be39.webp!color %}
{% galleryGroup '女孩' '我的女孩' '/posts/e19cb4b7.html#gallery-%E7%9B%B8%E5%86%8C' https://s3.qjqq.cn/47/661f3fcd06662.webp!color %}
</div>
<div class="gallery-group-main">
{% galleryGroup '壁紙' '收藏的一些壁紙' '/' https://s3.qjqq.cn/47/661f408a2be39.webp!color %}
{% galleryGroup '女孩' '我的女孩' '/posts/e19cb4b7.html#gallery-%E7%9B%B8%E5%86%8C' https://s3.qjqq.cn/47/661f3fcd06662.webp!color %}
</div>
```

**Comment by NooAcc** [comment]
> 有没有试过多个gallerygroup，逻辑是对的

我试过使用多gallerygroup。
多gallerygroup，虽然在定制化方面会更具有优势，但是感觉在便捷性上会差一些。

**Comment by NooAcc** [comment]
这算bug还是特性啊🤔
算特性的话，我还是老实用butterfly吧😭

**Comment by everfu** [comment]
可以按照参数支持换行，下个版本改
