### ISSUE TITLE
[Bug]: 手机端的“左下跳转按钮”点击无反应

### ISSUE THREAD

**Issue by ycccccccy** [everfu/hexo-theme-solitude#298]
### 前置确认

- [X] 我确认我运行的是最新版本的主题，并且安装了所需的依赖，在[FAQS](https://solitude-docs.efu.me/faq)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的Hexo版本是?

Hexo 7.0.0

### 你所使用的主题版本是稳定/最新?

稳定版（main）

### 问题描述 😯

只要是任意的手机端浏览器点击“左下跳转按钮”(主题配置文件中的hometop:下的group:项)都不会进行跳转，电脑端正常

**Comment by 3093113975** [comment]
可以提供一下截图吗?文字描述复现不了

**Comment by ycccccccy** [comment]
图中圈起来的按键，手机端任何浏览器点击都无反应
![微信图片_20240610115623](https://github.com/everfu/hexo-theme-solitude/assets/121854876/2e1485c8-2a97-4ef8-8ae6-8a1ca5cb7e60)

**Comment by everfu** [comment]
好的，下午修复

**Comment by Stars-harbor** [comment]
已更新至最新版，但我这里手机端似乎依旧不能正常打开。

在按钮附近长按后，甚至会选中下面配置的滚动图标的图片

![Screenshot_20240615_153539_com.huawei.browser.jpg](https://github.com/everfu/hexo-theme-solitude/assets/112921458/d218441a-8101-40d7-9a75-a5d7b6166287)

长按后显示如上图，点击在浏览器中打开则会显示为下图

![Screenshot_20240615_153548_com.huawei.browser.jpg](https://github.com/everfu/hexo-theme-solitude/assets/112921458/66eb5e01-1fa8-4d1d-9349-d7b0daa678e1)

**Comment by everfu** [comment]
好了
