### ISSUE TITLE
[Doc]: 主题的_config.yml到底以什么为准，配置文件本身和新文档不一致

### ISSUE THREAD

**Issue by AmenLi** [everfu/hexo-theme-solitude#301]
### 前置确认

- [X] 我确认我运行的是最新版本的主题，并且安装了所需的依赖，在[FAQS](https://solitude-docs.efu.me/faq)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的Hexo版本是?

Hexo 7.0.0

### 你所使用的主题版本是稳定/最新?

稳定版（main）

### 问题描述 😯

比如
1、侧边栏个人信息卡片的 `card` 项，配置文件里有 `style: 0 # 0: Heo样式 ：1: 设计样式`，但新文档里的示例并没有写
2、 `_config.yml`二维码项里是 `backcolor`，但文档里是`darkcolor: false`是拼错了，还是改了，看注释我感觉是改了
3、还有就是因为旧文档的文章没了，有的选项没有给出参数，不太会设置，比如二维码项里 `backface` ，尝试设置false，并没看见效果。

新文档里的配置示例，对页面元素有了新的命名，以便更好的区分，但主题的`_config.yml`还是旧版，是否能抽空同步一下。

**Comment by everfu** [comment]
抱歉，我有时间同步

**Comment by AmenLi** [comment]
好的，谢谢
