### ISSUE TITLE
[Feature]: 代码高亮

### ISSUE THREAD

**Issue by xiaoxiaoxiaoxiaocai** [everfu/hexo-theme-solitude#304]
### 功能简介

代码高亮没有solidity，我想要加上solidity

### 问题描述

代码高亮好像语言不全

### 实现效果

使solidity代码高亮

**Comment by everfu** [comment]
有没有他的官网？

**Comment by everfu** [comment]
<img width="994" alt="image" src="https://github.com/everfu/hexo-theme-solitude/assets/74389842/55991659-44b4-445b-b4f6-85ad8b51e0ba">

我不知道z这对不对

**Comment by everfu** [comment]
<img width="1017" alt="image" src="https://github.com/everfu/hexo-theme-solitude/assets/74389842/ab6c6006-5ec8-4f75-976b-8cbfcc1de810">

**Comment by xiaoxiaoxiaoxiaocai** [comment]
什么意思

**Comment by everfu** [comment]
有没有高亮颜色值参照

**Comment by xiaoxiaoxiaoxiaocai** [comment]
没有啊

**Comment by xiaoxiaoxiaoxiaocai** [comment]
![屏幕截图 2024-06-15 181235](https://github.com/everfu/hexo-theme-solitude/assets/131463449/40c496b1-ddac-4210-a21d-d9f37800b2d1)
我的还是不显示高亮

![屏幕截图 2024-06-15 181446](https://github.com/everfu/hexo-theme-solitude/assets/131463449/b13db950-d8de-4c6d-b377-288d888fc15d)

![屏幕截图 2024-06-15 181452](https://github.com/everfu/hexo-theme-solitude/assets/131463449/62264e07-761a-4bd9-9473-c43fbc977273)

**Comment by everfu** [comment]
highlight 识别不了 solidity 语言

**Comment by everfu** [comment]
更换成prismjs即可
<img width="994" alt="image" src="https://github.com/everfu/hexo-theme-solitude/assets/74389842/e2f94d0a-f033-468d-bf5d-3223f74c60bf">
<img width="308" alt="image" src="https://github.com/everfu/hexo-theme-solitude/assets/74389842/cb618842-04bb-4fc3-9b72-0688e0503b10">

**Comment by xiaoxiaoxiaoxiaocai** [comment]
![屏幕截图 2024-06-15 190239](https://github.com/everfu/hexo-theme-solitude/assets/131463449/63859d5d-02fd-4a25-a2e7-485f22a01884)
![屏幕截图 2024-06-15 190337](https://github.com/everfu/hexo-theme-solitude/assets/131463449/7ea5a604-d57c-4f9e-9899-a5b1a8c53f2a)

**Comment by everfu** [comment]
首次更换高亮需要 `hexo clean & hexo se` 清除缓存

**Comment by xiaoxiaoxiaoxiaocai** [comment]
ok，非常感谢
