### ISSUE TITLE
[Feature]: 一些小要求可以还原一下吗awa

### ISSUE THREAD

**Issue by mc-sep** [everfu/hexo-theme-solitude#309]
### 功能简介

PWA提示，弹窗提示，加载动画的优化

### 问题描述

1. 网站支持PWA，但是大多数人不知道，所以可以加一个提示：
![](https://img.zshfoj.com/a53d4c098ca4c4a5d64a3b28bc4e2158858f6ba03e9900783aa8dac05bda2a1b.png)

2. 比如说复制文字时的弹窗很枯燥，可以这样：（有点丑）

![](https://img.zshfoj.com/daba64db9264d070b1f2290d3b51848d468288ad8d6d3763a2db598c42f9f056.png)

3. 某些人进我们博客的加载页面的时候都不知道点一下，就一直在那里看着，可以这样：

![](https://img.zshfoj.com/246dd3587f4a81489e0f00c98b86022044ff3f4bdadcc492953a49d44181ea62.png)

### 实现效果

如上

**Comment by everfu** [comment]
这些都可以通过自定义实现

**Comment by mc-sep** [comment]
还是希望可以还原一下，毕竟我也在学hexo主题

**Comment by yife68** [comment]
都可通过自定js来实现，可自行摸索尝试

**Comment by everfu** [comment]
你可以自己做好然后出一个修改的教程
