### ISSUE TITLE
为手机端顶栏添加postchat按钮

### ISSUE THREAD

**Issue by Stars-harbor** [everfu/hexo-theme-solitude#310]
### 功能简介

便于手机端postchat的访问

### 问题描述

购买并成功向站点部署postchat后，进电脑端与平板端可在左下角显示postchat按钮，手机端无便捷入口，希望可以在顶栏增加一个按钮便于用户使用postchat（参考张洪heo手机端样式）

### 实现效果

当左下角可显示postchat按钮时，顶栏不显示该按钮，当左下角无法显示postchat时（手机端），顶栏常驻显示postchat按钮

### 其他内容

heo样式（未向上滑动）
![Screenshot_20240623_154424](https://github.com/everfu/hexo-theme-solitude/assets/112921458/2291e1a4-9fed-4818-93c3-17ad5d07eea8)
heo样式（向上滑动并开始显示已读百分比时）
![Screenshot_20240623_154435](https://github.com/everfu/hexo-theme-solitude/assets/112921458/35450813-d561-4212-9ef2-30d94cee3384)

**Comment by everfu** [comment]
自定义按钮，自行添加

**Comment by Stars-harbor** [comment]
定义按钮不是在手机端无法显示的吗？我看往的那个按钮就在手机端不显示

**Comment by Stars-harbor** [comment]
自昨晚起至此刻我给您回复，我已尝试修改了多个位置的代码，但因未系统学习过代码编程知识，我的数种尝试均无法满足“仅在手机端顶栏显示”这一要求。

我自己尝试修改pug、styl等文件时遇到的问题：

1. 仅能保证始终显示该按钮，但电脑端会出现ui重叠
2. 不论如何修改，该按钮即便处于nav-right分类下，但仍会显示在屏幕左下角，并不会出现在顶栏
3. 因其无法消失，导致该按钮会挡住手机端音乐馆的“顺序播放”按钮

我很清楚该功能是付费使用的，且我目前也已经购买了一年的时长，希望可以长期用下去。

即便可能购买该功能的潜在用户数量尚不清楚，但因为这样一个小问题却导致许多使用手机访问您的、我的站点的用户无法看到也无法使用这项功能，难免会给人一种钱白花了的感觉。

更何况postchat文档中的适配主题也只写了本主题（hexo框架），我也是秉承希望能让主题更完整、更优秀的目的才来向您提出此issue，真心希望您可以考虑在下个版本添加该功能
