### ISSUE TITLE
[Feature]: 去掉banner的icon限制

### ISSUE THREAD

**Issue by smallmayi** [everfu/hexo-theme-solitude#319]
### 功能简介

我想要开启banner后，不需要右边滚动的icon,现在没有icon报错

### 问题描述

![image](https://github.com/everfu/hexo-theme-solitude/assets/42774709/c52eccdd-4585-4e2e-b284-c307c6efe97a)
不需要里面的icon

### 实现效果

无

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/everfu) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/everfu/hexo-theme-solitude/issues/319">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/everfu/hexo-theme-solitude/issues/319/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/everfu/hexo-theme-solitude/issues/319/pledge.svg">
</picture>
</a>

**Comment by everfu** [comment]
已完成
