### ISSUE TITLE
[Bug]: 升级/更新代码执行后，主题未升级成功

### ISSUE THREAD

**Issue by daxiangyanxishe** [everfu/hexo-theme-solitude#325]
### 前置确认

- [X] 我确认我运行的是最新版本的主题，并且安装了所需的依赖，在[FAQS](https://solitude-docs.efu.me/faq)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Mac/Linux

### 运行的Hexo版本是?

Hexo 7.0.0

### 你所使用的主题版本是稳定/最新?

稳定版（main）

### 问题描述 😯

部署在自个服务器上的。使用“git pull”升级主题，提示“fatal: not a git repository (or any of the parent directories): .git
”。用“npm update hexo-theme-solitude”升级，提示
“up to date in 46s
38 packages are looking for funding
  run `npm fund` for details
”
![122](https://github.com/user-attachments/assets/af765be4-465c-4032-a63c-bcfa16c42a58)
![222](https://github.com/user-attachments/assets/318da32a-c35e-4bfb-8b60-aa17dc2a2725)

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/everfu) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/everfu/hexo-theme-solitude/issues/325">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/everfu/hexo-theme-solitude/issues/325/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/everfu/hexo-theme-solitude/issues/325/pledge.svg">
</picture>
</a>

**Comment by everfu** [comment]
你是怎么安装的主题？

**Comment by everfu** [comment]
仔细看文档，怎么安装的这么更新

**Comment by daxiangyanxishe** [comment]
坚持维持更新一个免费的主题，谢谢你！但能不能别把什么都往文档上推，群里是这样，这里还是这样，上面说了我是部署在自个服务器上的，你的文档安装里有讲怎么部署在服务的吗？有讲安装在服务器的主题怎么更新的吗？升级名利就是在你的文档看到的，总共就那几个升级命令，用过都不行。你这样还不如直接告诉我，我自个往服务器安装的不对，代码无法升级。  
注:博客一切正常，就是升级无法完成

**Comment by daxiangyanxishe** [comment]
我大概的安装步骤：在服务器安装了Nginx和Git,搭建Git仓库，然后给Git添加了ssh密钥，Git用户下创建Git仓库，配置自动部署。

**Comment by daxiangyanxishe** [comment]
那我就不用升级代码了，备份_config.solitude.yml。直接下载最新版覆盖旧版

**Comment by everfu** [comment]
你是把源码到上面还是生成后的

**Comment by everfu** [comment]
执行 `npm ls` 给我看源码结构

**Comment by daxiangyanxishe** [comment]
我记得是hexo d上传到宝塔新建的网站目录里的。你要的源码结构，我在第一次提问时是已经上传了源码结构截图的

**Comment by everfu** [comment]
你的问题和服务器不沾边，你的源码在本地，照你的报错应该是npm安装的，你先执行`npm un hexo-theme-solitude`然后执行
`npm i hexo-theme-solitude@1.13.3`，不知道谁是你用国内源的问题，并没有同步最新的版本

**Comment by daxiangyanxishe** [comment]
执行两个命令返回是这样的，主题没什么变化，是不是没成功
![3333](https://github.com/user-attachments/assets/87b10ac1-ad4a-46fd-940f-6a0299393afc)

**Comment by everfu** [comment]
你运行试试

**Comment by daxiangyanxishe** [comment]
![222](https://github.com/user-attachments/assets/a8584fff-8f49-4456-93b8-b2a43b0ee8f8)
与之前没什么变化

**Comment by daxiangyanxishe** [comment]
我有刚发现个事，执行 `npm ls`多了一个`+-- hexo-theme-solitude@1.13.3`，之前的没有
![Uploading 122.png…]()

**Comment by daxiangyanxishe** [comment]
我有刚发现个事，执行 `npm ls`多了一个`+-- hexo-theme-solitude@1.13.3`，之前没有
![122](https://github.com/user-attachments/assets/acd2ddc9-cd95-450d-a254-b1bd4848844c)

**Comment by everfu** [comment]
你的themes目录下有没有 solitude文件夹，有的话就删了

**Comment by daxiangyanxishe** [comment]
我删掉后，打开源码提示“无效 VCS 根映射目录<项目>\themes(solitude被注册为Git根，但在那里没有发现 Git 仓库。”我运行了一边，看到版本号是更改了。但引用放在`themes/solitude/source\img`图片全没了，我需要重新在本地下载新版solitude，放在themes目录吗

**Comment by everfu** [comment]
你的意思是你的图片放在主题目录下么，如果是主题内部资源更改，可以参考仓库里的内容进行修改，不需要再去下载

**Comment by daxiangyanxishe** [comment]
我删除了solitude，本地没有了，solitude去哪了。这我不知道i怎么更改了

**Comment by everfu** [comment]
要么你就安装文档的用 `Github` 方式安装一遍吧，npm的主题内容在node_module里

**Comment by everfu** [comment]
https://solitude.js.org/guide/quick-start.html#%E4%B8%BB%E9%A2%98%E5%AE%89%E8%A3%85

**Comment by daxiangyanxishe** [comment]
谢谢，我直接在本地`git clone -b main https://github.com/everfu/hexo-theme-solitude.git themes/solitude`然后对比修改`_config.solitude.yml`了。
