### ISSUE TITLE
[Bug]: {% gallery %} 语法渲染出来的图片被折叠

### ISSUE THREAD

**Issue by Qxiaoqi** [everfu/hexo-theme-solitude#350]
### 前置确认

- [X] 我确认我运行的是最新版本的主题，并且安装了所需的依赖，在[FAQS](https://solitude-docs.efu.me/faq)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Mac/Linux

### 运行的Hexo版本是?

Hexo 7.0.0

### 你所使用的主题版本是稳定/最新?

稳定版（main）

### 问题描述 😯

【表现】

{% gallery %} 语法渲染出来的图片被折叠，窗口 resize 之后恢复

图示最左列，和中间列，三个图片折叠展示

【截图如下】
<img width="1031" alt="image" src="https://github.com/user-attachments/assets/69560bd1-6330-420f-8fc8-685586259cce">

这里的 position 没在代码中找到对应的位置，不太清楚这里的逻辑。水平有限没办法继续排查了。感谢作者。

【其他】
图片大小：平均 700kb 左右
大概在 10 图片张以上，会出现这个问题

### 终端日志 📒

INFO  Validating config
INFO  
  ===================================================================
       #####  ####  #     #####  ###### #     # ######   ######
      #      #    # #       #      #    #     # #      # #
       ##### #    # #       #      #    #     # #      # ######
           # #    # #       #      #    #     # #      # #
      ######  ####  ##### #####    #      ###   ######   ######
                            2.0.5
  ===================================================================
  GitHub: https://github.com/everfu/hexo-theme-solitude
  
INFO  Start processing
INFO  Hexo is running at http://localhost:4000/ . Press Ctrl+C to stop.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/everfu) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/everfu/hexo-theme-solitude/issues/350">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/everfu/hexo-theme-solitude/issues/350/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/everfu/hexo-theme-solitude/issues/350/pledge.svg">
</picture>
</a>

**Comment by everfu** [comment]
图太大了

**Comment by Qxiaoqi** [comment]
> 图太大了

有办法优化一下这里吗，图片用相机照的，10M 左右压缩到 700kb 了，再压缩就只能先缩放图片了，感谢回复。

**Comment by Qxiaoqi** [comment]
压缩到 100kb 左右的时候好了很多，但是在图片比较多的时候（比如10张以上），还是会有这种情况

**Comment by everfu** [comment]
更新最新版试试吧，解决了

**Comment by Qxiaoqi** [comment]
已经解决，非常感谢！
