### ISSUE TITLE
[Bug]: 多人互动标识翻页不显示

### ISSUE THREAD

**Issue by Stars-harbor** [everfu/hexo-theme-solitude#359]
### 前置确认

- [X] 我确认我运行的是最新版本的主题，并且安装了所需的依赖，在[FAQS](https://solitude-docs.efu.me/faq)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的Hexo版本是?

Hexo 7.0.0

### 你所使用的主题版本是稳定/最新?

稳定版（main）

### 问题描述 😯

开启多人互动后，该标识仅在第一页出现，自第二页文章起即使符合显示条件依旧不会出现该标识

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/everfu) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/everfu/hexo-theme-solitude/issues/359">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/everfu/hexo-theme-solitude/issues/359/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/everfu/hexo-theme-solitude/issues/359/pledge.svg">
</picture>
</a>

**Comment by everfu** [comment]
不会，都显示

**Comment by Stars-harbor** [comment]
实测，不显示，我的第二页第一篇文章即符合我设定的10条评论要求，但它并没有出现该标识https://blog.starsharbor.com/page/2/

**Comment by yife68** [comment]
偶现情况下，输出数量会小于实际数量，此导致的问题。
