### ISSUE TITLE
[Bug]: 写入md的图片不显示？

### ISSUE THREAD

**Issue by rumian0** [everfu/hexo-theme-solitude#366]
### 前置确认

- [X] 我确认我运行的是最新版本的主题，并且安装了所需的依赖，在[FAQS](https://solitude-docs.efu.me/faq)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的Hexo版本是?

Hexo 7.0.0

### 你所使用的主题版本是稳定/最新?

稳定版（main）

### 问题描述 😯

是这样的，用vc可以查看图片
![image](https://github.com/user-attachments/assets/0ca81eb8-bde1-4b26-b661-1cdd3fa147f9)
浏览器中看不见图片，搜了各种方法都没有效果
![image](https://github.com/user-attachments/assets/fae1c24c-2eed-4e7a-a731-0b4acd46111e)
上面的置顶图也没有，之前是有的，弄了一些方法让后就看不见了
![image](https://github.com/user-attachments/assets/c9c5f897-bfb4-4c17-9905-d476c40c8bad)
这个访问量为什莫显示不出来
作者有时间的话，麻烦您看看能不能解决

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/everfu) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/everfu/hexo-theme-solitude/issues/366">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/everfu/hexo-theme-solitude/issues/366/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/everfu/hexo-theme-solitude/issues/366/pledge.svg">
</picture>
</a>

**Comment by everfu** [comment]
控制台有报错阻拦了，提供一下线上地址
