### ISSUE TITLE
[Bug]: 新版本首页样式显示存在问题

### ISSUE THREAD

**Issue by Stars-harbor** [everfu/hexo-theme-solitude#369]
### 前置确认

- [X] 我确认我运行的是最新版本的主题，并且安装了所需的依赖，在[FAQS](https://solitude-docs.efu.me/faq)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的Hexo版本是?

Hexo 7.0.0

### 你所使用的主题版本是稳定/最新?

稳定版（main）

### 问题描述 😯

在过去的新版本更新中，hometop的css文件中新增了min-width fit-content这样一个配置，但目前配置六篇推荐文章后，电脑端该部分列表反而出现了显示异常，我尝试在F12中禁用该内容后显示正常，辛苦检查该部分值是否可以调整或删除（为保证观看体验我已暂时删除该项）

截图如下：

![72818a96499700996c9a0b7aa30b0ba9](https://github.com/user-attachments/assets/fe99b970-2118-4f05-bf6d-978bae9bed82)
↑开启该内容后显示异常

![477e953e659265ba590129d5ed36b276](https://github.com/user-attachments/assets/79bd1fed-958b-4230-8df5-9dfd4cc15a9b)
↑关闭后显示正常

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/everfu) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/everfu/hexo-theme-solitude/issues/369">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/everfu/hexo-theme-solitude/issues/369/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/everfu/hexo-theme-solitude/issues/369/pledge.svg">
</picture>
</a>

**Comment by everfu** [comment]
实际并不会，自行查看预览地址：https://solitude.js.org/preview/zh
注意对比我修改的文件
