### ISSUE TITLE
[Feature]: 手動設置文章的封面顏色

### ISSUE THREAD

**Issue by BlueWhaleYT** [everfu/hexo-theme-solitude#374]
### 功能简介

我想要手動設置文章的封面顏色

### 问题描述

目前封面顏色都是透過 API 形式來擷取的，希望可以新增一個 `mode` 是可以手動設置文章的封面顏色，啟動這個模式後，可從文章的 front matter 中設置，如 `color` 就可以為該文章設置封面顏色。

### 实现效果

```yml
---
title: ...
date: ...
color: "#f78c6c"
---

...
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/everfu) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/everfu/hexo-theme-solitude/issues/374">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/everfu/hexo-theme-solitude/issues/374/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/everfu/hexo-theme-solitude/issues/374/pledge.svg">
</picture>
</a>

**Comment by everfu** [comment]
已添加，请在dev尝试后进行反馈
