### ISSUE TITLE
[Bug]: 双评论无切换按钮

### ISSUE THREAD

**Issue by Linux-qitong** [everfu/hexo-theme-solitude#380]
### 前置确认

- [X] 我确认我运行的是最新版本的主题，并且安装了所需的依赖，在[FAQS](https://solitude-docs.efu.me/faq)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Mac/Linux

### 运行的Hexo版本是?

Hexo 7.0.0

### 你所使用的主题版本是稳定/最新?

开发板 (dev)

### 问题描述 😯

![Image_1725737253358](https://github.com/user-attachments/assets/7b12aa72-4fc7-4999-9d83-4a338dc89ee8)
正常应该是
<img width="1454" alt="322040272-d03bcd04-3b34-4932-997c-20468c3eefee" src="https://github.com/user-attachments/assets/e7676564-589f-44ff-b61b-9945bf934090">
之前在群里反馈过，到现在还是没有切换按钮，试过giscus和twikoo，出现两个评论框，twikoo和giscus只出现twikoo。
评论框的机制应该是有问题的

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/everfu) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/everfu/hexo-theme-solitude/issues/380">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/everfu/hexo-theme-solitude/issues/380/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/everfu/hexo-theme-solitude/issues/380/pledge.svg">
</picture>
</a>

**Comment by everfu** [comment]
好了，拉取试试
