### ISSUE TITLE
[Bug]: 池塘无法加载，钓鱼可以加载并读到数据

### ISSUE THREAD

**Issue by AGEN233** [everfu/hexo-theme-solitude#385]
### 前置确认

- [X] 我确认我运行的是最新版本的主题，并且安装了所需的依赖，在[FAQS](https://solitude-docs.efu.me/faq)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的Hexo版本是?

Hexo 7.0.0

### 你所使用的主题版本是稳定/最新?

稳定版（main）

### 问题描述 😯

hexo:7.3.0
主题:2.0.12
demo:agen233.top/fcircle
GithubPage和本地部署中，均无法加载池塘信息，池塘部署方式是根据https://solitude.js.org/preview/zh/posts/d3883050.html的教程进行配置。
确定api配置正确无误，在butterfly+林木木方案中可以正常加载。

![image](https://github.com/user-attachments/assets/ec64cdcb-5e9e-4017-ba20-82ebba2e0f3a)

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/everfu) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/everfu/hexo-theme-solitude/issues/385">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/everfu/hexo-theme-solitude/issues/385/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/everfu/hexo-theme-solitude/issues/385/pledge.svg">
</picture>
</a>

**Comment by AGEN233** [comment]
> 请看后台报错

后台完全没报错，hexodebug无报错、前端无报错、hexofriends无报错（

**Comment by everfu** [comment]
教程最底下有一个完整代码，直接复制然后修改api地址使用就可以了

**Comment by everfu** [comment]
https://blog.byer.top/fcircle/
这有个示例

**Comment by AGEN233** [comment]
> 教程最底下有一个完整代码，直接复制然后修改api地址使用就可以了

这就奇了怪了，我就是用的完整代码（
![image](https://github.com/user-attachments/assets/1161551a-2dea-4cc3-a743-1ca0c53050c8)

**Comment by everfu** [comment]
这问题直接去群里问
