### ISSUE TITLE
[Feature]: 手机端TOC

### ISSUE THREAD

**Issue by Loudomian** [everfu/hexo-theme-solitude#386]
### 功能简介

手机上 TOC（目录）功能的问题

### 问题描述

我注意到在手机设备上浏览文章时，没有TOC转跳，没法快速定位长篇文章的对应位置。

### 实现效果

考虑到菜单栏已经被其他功能占满，可以把回到顶部的按钮改成展开目录页面，原有的回到顶部功能可以改成在把目录页面底部固定一个回到顶部的按钮。

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/everfu) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/everfu/hexo-theme-solitude/issues/386">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/everfu/hexo-theme-solitude/issues/386/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/everfu/hexo-theme-solitude/issues/386/pledge.svg">
</picture>
</a>

**Comment by everfu** [comment]
已添加，具体等待文档更新
