### ISSUE TITLE
[Bug]: bing站长工具无法test live url，无法抓取robots.txt

### ISSUE THREAD

**Issue by leaflyingl** [everfu/hexo-theme-solitude#388]
### 前置确认

- [X] 我确认我运行的是最新版本的主题，并且安装了所需的依赖，在[FAQS](https://solitude-docs.efu.me/faq)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的Hexo版本是?

Hexo 7.0.0

### 你所使用的主题版本是稳定/最新?

稳定版（main）

### 问题描述 😯

bing搜索引擎无法检测网站url
版本是2.0.13
<img width="558" alt="1727191561940" src="https://github.com/user-attachments/assets/9fc05892-b098-467e-b6ea-290996081462">

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/everfu) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/everfu/hexo-theme-solitude/issues/388">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/everfu/hexo-theme-solitude/issues/388/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/everfu/hexo-theme-solitude/issues/388/pledge.svg">
</picture>
</a>

**Comment by everfu** [comment]
reboot.txt放在source文件夹下就行了，这与主题没多大关系

**Comment by leaflyingl** [comment]
> robots.txt放在source文件夹下就行了，这与主题没多大关系

robots.txt OK 了，但是bing还是没法 test live url，不知道什么问题
