### ISSUE TITLE
[Feature]: 请问能否支持使用umami来代替51a的数据统计？

### ISSUE THREAD

**Issue by lingzs13** [everfu/hexo-theme-solitude#391]
### 功能简介

参考heo的umami配置来代替51a统计

### 问题描述

参考heo的umami配置来代替51a统计

### 实现效果

参考heo的umami配置来代替51a统计

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/everfu) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/everfu/hexo-theme-solitude/issues/391">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/everfu/hexo-theme-solitude/issues/391/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/everfu/hexo-theme-solitude/issues/391/pledge.svg">
</picture>
</a>

**Comment by everfu** [comment]
更新2.0以上就能有，早就内置了
