### ISSUE TITLE
[Bug]: 关闭控制台时音乐胶囊无法正常播放音乐

### ISSUE THREAD

**Issue by HPCesia** [everfu/hexo-theme-solitude#395]
### 前置确认

- [X] 我确认我运行的是最新版本的主题，并且安装了所需的依赖，在[FAQS](https://solitude-docs.efu.me/faq)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的Hexo版本是?

Hexo 7.0.0

### 你所使用的主题版本是稳定/最新?

开发板 (dev)

### 问题描述 😯

在主题配置文件中关闭 `console` 并开启 `capsule` 时，音乐胶囊会无法使用，且 F12 控制台报错：
![image](https://github.com/user-attachments/assets/a9ce2ac2-0d83-4845-98ef-9728cbbc7642)
配置文件：
```yaml
# Console
# 控制台
console:
  enable: false
# Capsule music
# 音乐胶囊
capsule:
  enable: true
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/everfu) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/everfu/hexo-theme-solitude/issues/395">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/everfu/hexo-theme-solitude/issues/395/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/everfu/hexo-theme-solitude/issues/395/pledge.svg">
</picture>
</a>

**Comment by everfu** [comment]
已修复
