### ISSUE TITLE
[Feature]: gallery标签下的图片，在加载的时候挤在一起，加载完后才排版

### ISSUE THREAD

**Issue by Rakiendesu** [everfu/hexo-theme-solitude#397]
### 功能简介

可不可以修改为懒加载方式，像butterfly那样

### 问题描述

 gallery标签下的图片，在加载的时候挤在一起，加载完后才排版，图片一多会影响用户体验

### 实现效果

可以先加载一部分，加个“加载更多”等字样的按钮，或者像butterfly那样滚动加载

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/everfu) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/everfu/hexo-theme-solitude/issues/397">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/everfu/hexo-theme-solitude/issues/397/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/everfu/hexo-theme-solitude/issues/397/pledge.svg">
</picture>
</a>

**Comment by Rakiendesu** [comment]
https://github.com/user-attachments/assets/8e2757e0-4812-4fa6-be9b-acce09c58da4

这样，图片多或者网不好会卡住很久

> 你好，逻辑是当加载完并排版好才会显示，你说的这种情况不会有，请你发出视频

**Comment by everfu** [comment]
提供一下线上地址，或者把标签内图片发出来我试试

**Comment by Rakiendesu** [comment]
> 提供一下线上地址，或者把标签内图片发出来我试试

https://rakien.netlify.app/gallery

**Comment by everfu** [comment]
稍后就会更新，已解决
