### ISSUE TITLE
[Bug]: 切换颜色giscus不跟随切换

### ISSUE THREAD

**Issue by Linux-qitong** [everfu/hexo-theme-solitude#398]
### 前置确认

- [X] 我确认我运行的是最新版本的主题，并且安装了所需的依赖，在[FAQS](https://solitude-docs.efu.me/faq)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Mac/Linux

### 运行的Hexo版本是?

Hexo 7.0.0

### 你所使用的主题版本是稳定/最新?

开发板 (dev)

### 问题描述 😯

得退出对应页面重新打开，能跟随切换，单评论，双评论都是
双评论下开启懒加载giscus不加载，单评论没问题
giscus为主双评论，懒加载可以出现

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/everfu) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/everfu/hexo-theme-solitude/issues/398">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/everfu/hexo-theme-solitude/issues/398/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/everfu/hexo-theme-solitude/issues/398/pledge.svg">
</picture>
</a>

**Comment by everfu** [comment]
能提供一下giscus地址吗，我测试下

**Comment by Linux-qitong** [comment]
https://giscus.app/zh-CN

**Comment by Linux-qitong** [comment]
https://blog.ysboke.cn/posts/blog/giscus/#:~:text=1%E3%80%81%E6%8F%90%E5%89%8D%E5%88%9B%E5%BB%BA%E5%A5%BD%E4%B8%80%E4%B8%AA%E7%A9%BA
