### ISSUE TITLE
[Feature]: 优化postchat上传逻辑

### ISSUE THREAD

**Issue by Stars-harbor** [everfu/hexo-theme-solitude#401]
### 功能简介

调整postchat上传逻辑，对标原项目，增加自定义项

### 问题描述

经过我的长期实验，目前postchat开启后存在以下问题：

1. 会异常上传所有页面
2. 会异常上传各页面顶部导航栏按钮（甚至存在多个仅上传了导航栏按钮文字，无其他任何内容）
3. 会异常上传大量胶囊音乐的歌词
4. 会异常上传多次相同页面
5. 关闭了ai摘要的页面（ai: false）也会跟随上传，继而导致对应文章ai仍有一定概率异常出现在页面上

由于以上异常，导致postchat用户会经常向上重新发起请求，造成同一篇文章有4、5个ai摘要的情况，继而导致上级数据库混乱，postchat无法给出正确答案，失去购买的意义

### 实现效果

按照原项目的最新进展，建议优先实现以下功能：

1. 自主控制postchat与post-ai的文章选择器（postSelector），以确保不会因胶囊音乐变动而多次上传同一页面（设置一个即可）
2. 自主控制postchat与post-ai上传给tianli-gpt的文章链接格式（postURL），以确保非文章页不会上传（设置一个即可）
3. 当ai摘要设置为关闭时，postchat与post-ai均不再上传此文章（此地址）

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/everfu) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/everfu/hexo-theme-solitude/issues/401">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/everfu/hexo-theme-solitude/issues/401/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/everfu/hexo-theme-solitude/issues/401/pledge.svg">
</picture>
</a>

**Comment by Stars-harbor** [comment]
**特别补充：此问题已进行反复确认，证实存在，且现有config中并无可实现以上要求的配置项，全局检索代码中也未见postSelector内容。该问题在且仅在postchat功能上显现严重，未升级前（即post-ai）未见显著异常，请勿因post-ai未见异常即草率回复无异常或关闭本issue**

**Comment by everfu** [comment]
去找heo

**Comment by everfu** [comment]
配置项里有提供自定义，拉黑某些文章提供黑名单列表就是了
