### ISSUE TITLE
[Feature]: 關於簡繁轉換和其他語種翻譯的問題

### ISSUE THREAD

**Issue by kdglobalcom** [everfu/hexo-theme-solitude#402]
### 功能简介

我想要網頁上除了簡繁轉換外，還可以進行中英翻譯

### 问题描述

我閱讀了代碼後
```
function Traditionalized(cc) {
        const ss = JTPYStr();
        const tt = FTPYStr();
        return Array.from(cc).map(char => {
            const index = ss.indexOf(char);
            return index > -1 ? tt.charAt(index) : char;
        }).join('');
    }

    function Simplized(cc) {
        const ss = JTPYStr();
        const tt = FTPYStr();
        return Array.from(cc).map(char => {
            const index = tt.indexOf(char);
            return index > -1 ? ss.charAt(index) : char;
        }).join('');
    }
```
了解了網頁上的轉換為繁體、轉換為簡體，是使用模組進行轉換的。
我知道應該沒有一個模組可以直接套用中英的翻譯，即使有，效果和文法也會有所差異。
主要想問問博主有什麼方式可以做到這件事。

### 实现效果

網頁上的「自定义右键菜单」可以多一個選項為轉換為英文 / 其他語種。

### 其他内容

路徑：/js/tw_cn.js

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/everfu) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/everfu/hexo-theme-solitude/issues/402">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/everfu/hexo-theme-solitude/issues/402/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/everfu/hexo-theme-solitude/issues/402/pledge.svg">
</picture>
</a>

**Comment by everfu** [comment]
1. 引入谷歌网站翻译
2. 一式两份做中英两个网站合并

**Comment by everfu** [comment]
有问题自行百度
