### ISSUE TITLE
[Feature]: 加载头像希望可以自定义

### ISSUE THREAD

**Issue by Linux-qitong** [everfu/hexo-theme-solitude#410]
### 功能简介

加载头像默认引用网站图标

### 问题描述

希望引用设置的头像，我自己用css修改，结果是网页图标和头像一起显示，我大上周修改，效果惨不忍睹
有些用户头像和网页图标不一样，不应该默认引用网页图标，引用头像或者加入自定义

### 实现效果

引用头像加载

### 你想到的可行的替代方案

我自己修改pug，交流群有记录，结果失败了

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/everfu) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/everfu/hexo-theme-solitude/issues/410">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/everfu/hexo-theme-solitude/issues/410/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/everfu/hexo-theme-solitude/issues/410/pledge.svg">
</picture>
</a>

**Comment by everfu** [comment]
已添加
