### ISSUE TITLE
[Bug]: about页面报异常

### ISSUE THREAD

**Issue by oojun** [everfu/hexo-theme-solitude#422]
### 前置确认

- [X] 我确认我运行的是最新版本的主题，并且安装了所需的依赖，在[FAQS](https://solitude-docs.efu.me/faq)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的Hexo版本是?

Hexo 7.0.0

### 你所使用的主题版本是稳定/最新?

稳定版（main）

### 问题描述 😯

在2.1.8主题，about页面，控制台抛出异常，初步定位是tenyear函数异常

### 终端日志 📒

![QQ20241125-003553](https://github.com/user-attachments/assets/25f45791-dbb2-4b13-a78f-228900410cce)

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/everfu) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/everfu/hexo-theme-solitude/issues/422">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/everfu/hexo-theme-solitude/issues/422/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/everfu/hexo-theme-solitude/issues/422/pledge.svg">
</picture>
</a>

**Comment by everfu** [comment]
0ab16c0ec82d90a259644175a172350a61150672
