### ISSUE TITLE
[Bug]: 使用video插件标签视频显示过大

### ISSUE THREAD

**Issue by manman-dong** [everfu/hexo-theme-solitude#426]
### 前置确认

- [X] 我确认我运行的是最新版本的主题，并且安装了所需的依赖，在[FAQS](https://solitude-docs.efu.me/faq)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的Hexo版本是?

Hexo 7.0.0

### 你所使用的主题版本是稳定/最新?

稳定版（main）

### 问题描述 😯

显示效果：

![image](https://github.com/user-attachments/assets/83db23de-0521-42d2-bbbf-86d19db934d4)

第一个视频为1080p，第二个视频是480p

第一个视频显示视频尺寸巨大，第二个视频显示很小，而且显示偏左，如果是360p会显示更小

能否使插入博客之中的视频固定尺寸，并且让视频居中显示呢

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/everfu) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/everfu/hexo-theme-solitude/issues/426">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/everfu/hexo-theme-solitude/issues/426/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/everfu/hexo-theme-solitude/issues/426/pledge.svg">
</picture>
</a>

**Comment by everfu** [comment]
去插件下提issue
