### ISSUE TITLE
[Feature]: 移动端侧边显示最近评论

### ISSUE THREAD

**Issue by Linux-qitong** [everfu/hexo-theme-solitude#428]
### 功能简介

让其在移动端正常显示最近评论，点击还能转跳最近评论

### 问题描述

![Screenshot_2024-12-15-07-35-03-04_a252b927494330cdc2c8ba3b3f952e5e](https://github.com/user-attachments/assets/c3123951-675d-4fba-908f-03aa91cc6a7e)

### 实现效果

![Screenshot_2024-12-15-07-36-22-68_a252b927494330cdc2c8ba3b3f952e5e](https://github.com/user-attachments/assets/a24822c3-6aec-4a33-9205-0b4aef7526a0)
实现效果如图

### 你想到的可行的替代方案

应该是改移动端侧边相关的

### 其他内容

移动端那个侧边栏不知道洪哥怎么做到的，显示最近评论，也去看了其他使用主题的用户都没有这个功能

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/everfu) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/everfu/hexo-theme-solitude/issues/428">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/everfu/hexo-theme-solitude/issues/428/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/everfu/hexo-theme-solitude/issues/428/pledge.svg">
</picture>
</a>

**Comment by yife68** [comment]
已推送至Dev开发版。该功能除“twikoo”评论系统外，其余评论系统均未进行测试。
