### ISSUE TITLE
参照文档开启KaTeX公式渲染时提示包不存在

### ISSUE THREAD

**Issue by Qiu-Quanzhi** [everfu/hexo-theme-solitude#431]
### 前置确认

- [X] 我确认我运行的是最新版本的主题，并且安装了所需的依赖，在[FAQS](https://solitude-docs.efu.me/faq)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的Hexo版本是?

Hexo 7.0.0

### 你所使用的主题版本是稳定/最新?

稳定版（main）

### 问题描述 😯

在参阅该段落（开启KaTeX公式渲染）并试图安装相应模块时出错：
https://solitude.js.org/zh/config/extend#%E6%95%B0%E5%AD%A6%E5%85%AC%E5%BC%8F

原因：找不到 hexo-markdown-it 模块（已经排除镜像源问题）

### 终端日志 📒

PS D:\home> npm i hexo-markdown-it @renbaoshuo/markdown-it-katex
npm error code E404
npm error 404 Not Found - GET https://registry.npmjs.org/hexo-markdown-it - Not found
npm error 404
npm error 404  'hexo-markdown-it@*' is not in this registry.
npm error 404
npm error 404 Note that you can also install from a
npm error 404 tarball, folder, http url, or git url.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/everfu) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/everfu/hexo-theme-solitude/issues/431">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/everfu/hexo-theme-solitude/issues/431/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/everfu/hexo-theme-solitude/issues/431/pledge.svg">
</picture>
</a>

**Comment by Qiu-Quanzhi** [comment]
为了解决公式渲染问题看过这篇 issue 的说明，但链接已失效：

              使用 进阶版的 markdown渲染器请看作者博客介绍：[Solitude 数学公式](https://blog.wzsco.top/p/b1d1f75b.html)

_Originally posted by @everfu in https://github.com/everfu/hexo-theme-solitude/issues/116#issuecomment-1911616559_

**Comment by everfu** [comment]
改了
