### ISSUE TITLE
开启文章过期提醒报错（未解决）

### ISSUE THREAD

**Issue by Qiu-Quanzhi** [everfu/hexo-theme-solitude#432]
### 前置确认

- [X] 我确认我运行的是最新版本的主题，并且安装了所需的依赖，在[FAQS](https://solitude-docs.efu.me/faq)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的Hexo版本是?

Hexo 7.0.0

### 你所使用的主题版本是稳定/最新?

稳定版（main）

### 问题描述 😯

设定相关选项后，未能开启文章过期提醒

观察发现该选项开启后，控制台报错。

### 终端日志 📒

web控制台
---
Uncaught TypeError: Cannot read properties of null (reading 'insertAdjacentElement')
    at tabs.expireAddListener (main.js?v=2.1.13:702:22)
    at window.refreshFn (main.js?v=2.1.13:757:10)
    at HTMLDocument.<anonymous> (VM95:18:12)
    at pjax.min.js:1:8641
    at module.exports (pjax.min.js:1:9395)
    at pjax.min.js:1:8504
    at Array.forEach (<anonymous>)
    at module.exports (pjax.min.js:1:8314)
    at Pjax.afterAllSwitches (pjax.min.js:1:5129)
    at Pjax.onSwitch (pjax.min.js:1:2923)

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/everfu) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/everfu/hexo-theme-solitude/issues/432">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/everfu/hexo-theme-solitude/issues/432/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/everfu/hexo-theme-solitude/issues/432/pledge.svg">
</picture>
</a>

**Comment by everfu** [comment]
已解决
