### ISSUE TITLE
[Bug]: 文章页busuanzi pv数据获取不到，一直转圈圈

### ISSUE THREAD

**Issue by Mengqyzh** [everfu/hexo-theme-solitude#442]
### 前置确认

- [X] 我确认我运行的是最新版本的主题，并且安装了所需的依赖，在[FAQS](https://solitude-docs.efu.me/faq)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的Hexo版本是?

Hexo 7.0.0

### 你所使用的主题版本是稳定/最新?

稳定版（main）

### 问题描述 😯

文章页busuanzi pv数据获取不到，一直转圈圈
![screenshot_2024-12-19_17-22-05](https://github.com/user-attachments/assets/32c8297e-ab49-4088-aa6e-d54958994cd0)

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/everfu) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/everfu/hexo-theme-solitude/issues/442">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/everfu/hexo-theme-solitude/issues/442/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/everfu/hexo-theme-solitude/issues/442/pledge.svg">
</picture>
</a>

**Comment by Mengqyzh** [comment]
测试后发现，侧边栏网站信息模块的pv、uv数据关闭后，文章元信息的pv数据无法正常显示

**Comment by Stars-harbor** [comment]
文章页内pv可以使用评论系统进行统计（已知twikoo评论可行）
网站总数据显示不了可能是busuanzi在国内速度不加，有条件可以自建或者使用他人搭建的公益busuanzi

**Comment by Qiu-Quanzhi** [comment]
逻辑层和展示层条件不统一导致的，
似乎这热度的逻辑和侧栏设定耦合了
``` layout\includes\inject\body.pug
    if theme.busuanzi && (theme.aside.siteinfo.uv || theme.aside.siteinfo.pv)
      script(defer pjax src=url_for(theme.cdn.busuanzi_js))
```
``` layout\includes\widgets\post\postInfo.pug
if theme.busuanzi
                            if theme.busuanzi_use === 0
                                span#busuanzi_value_page_pv
                                    i.solitude.fa-solid.fa-spinner.fa-spin
                            else
                                span#busuanzi_page_pv
                                    i.solitude.fa-solid.fa-spinner.fa-spin
```

**Comment by Qiu-Quanzhi** [comment]
#449 应该解决此问题
