### ISSUE TITLE
[Feature]: 页脚头像希望可以自定义或跟随头像，而不是网页图标

### ISSUE THREAD

**Issue by Linux-qitong** [everfu/hexo-theme-solitude#444]
### 功能简介

目前我在自己的solidute上面魔改实现了

### 问题描述

这是修改的参数img.author-avatar(src=url_for(theme.loading.favicon || theme.site.icon))
参考的加载头像自定义，引用的是加载头像的设置

### 实现效果

引用头像，而不是网页图标

### 你想到的可行的替代方案

可以把自定义加载头像的设置项和设置页脚显示头像的设置项放在一起，这样简洁一些。

**Comment by Qiu-Quanzhi** [comment]
> ### 功能简介
> 目前我在自己的solidute上面魔改实现了
> 
> ### 问题描述
> 这是修改的参数img.author-avatar(src=url_for(theme.loading.favicon || theme.site.icon)) 参考的加载头像自定义，引用的是加载头像的设置
> 
> ### 实现效果
> 引用头像，而不是网页图标
> 
> ### 你想到的可行的替代方案
> 可以把自定义加载头像的设置项和设置页脚显示头像的设置项放在一起，这样简洁一些。
> 
> ### 其他内容
> _No response_

有点怪

不如考虑用 `theme.card.author.avatar`？

**Comment by Qiu-Quanzhi** [comment]
就设计而言，还是保持 site icon 就好
