### ISSUE TITLE
[Bug]: 没有pjax

### ISSUE THREAD

**Issue by Linux-qitong** [everfu/hexo-theme-solitude#459]
### 前置确认

- [X] 我确认我运行的是最新版本的主题，并且安装了所需的依赖，在[FAQS](https://solitude-docs.efu.me/faq)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Mac/Linux

### 运行的Hexo版本是?

Hexo 7.0.0

### 你所使用的主题版本是稳定/最新?

开发板 (dev)

### 问题描述 😯

切换页面歌曲播放中断

**Comment by everfu** [comment]
自己魔改破坏了 pjax 环境

**Comment by Linux-qitong** [comment]
部分地方pjax失效，切换音乐中断

**Comment by Linux-qitong** [comment]
用的原版demo，我特意下载下来本地测试的dev,遇到问题我基本上都会在原版测试
