### ISSUE TITLE
[Bug]: 当滚动容器元素很多时，滚速起飞

### ISSUE THREAD

**Issue by Qiu-Quanzhi** [everfu/hexo-theme-solitude#466]
### 前置确认

- [X] 我确认我运行的是最新版本的主题，并且安装了所需的依赖，在[FAQS](https://solitude-docs.efu.me/faq)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的Hexo版本是?

Hexo 6.3.0及以下

### 你所使用的主题版本是稳定/最新?

开发板 (dev)

### 问题描述 😯

将静态的滚动动画时间改为动态调整

**Comment by Oilan94** [comment]
我也发现这个问题了，因为看不懂，所以手动改了技能点相关的动画时间哈哈
